services:
  - type: web
    name: angular-universal-app
    env: node
    buildCommand: npm install && npm run build:ssr
    startCommand: npm run serve:ssr
    envVars:
      - key: NODE_VERSION
        value: 18.18.0