services:
  - type: web
    name: angular-universal-app
    env: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
